// AUTO-GENERATED by scripts/generate-registry.js — do not edit manually
import { registerModule } from './registry';
import DiscordModule from './installed/discord';
import ObsModule from './installed/obs';
import TwitchModule from './installed/twitch';

// Modules checked out as submodules, compiled into this build.
export default function registerSourceModules() {
  registerModule(DiscordModule);
  registerModule(ObsModule);
  registerModule(TwitchModule);
}
